#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

#define ECU_CYCLE_MS 100U
#define WATCHDOG_TIMEOUT_MS 1000U

#define TEMP_WARN_C 110.0f
#define TEMP_FAULT_C 130.0f
#define TEMP_CLEAR_C 125.0f

#define RPM_WARN 5000U
#define RPM_FAULT 6000U
#define RPM_CLEAR 5500U

#define VOLTAGE_WARN_LOW 12.0f
#define VOLTAGE_WARN_HIGH 14.5f
#define VOLTAGE_UNDER_FAULT 11.0f
#define VOLTAGE_UNDER_CLEAR 11.5f
#define VOLTAGE_OVER_FAULT 15.0f
#define VOLTAGE_OVER_CLEAR 14.5f

#define FAULT_DEBOUNCE_SAMPLES 2U
#define BATTERY_DIVIDER_RATIO 6.0f

#endif
